import { useQuery } from "@tanstack/react-query";
import Head from "next/head";
import { useEffect, useState } from "react";
import AddAuctionBtn from "../components/add-auction-btn.component";
import AddAuctionDialog from "../components/add-auction-dialog.component";
import AuctionComponent from "../components/auction.component";
import AuctionSearch from "../components/auctionSearch.component";
import Layout from "../components/layout.component";
import Overlay from "../components/overlay.component";
import { useUser } from "../hooks/use-user.hook";
import { Auction } from "../utils/types.util";
import {
  getAuctions,
  getIsAdmin,
  getTokenById,
  getTokensByUid,
} from "../utils/firebase.util";
import { Token } from "../utils/types.util";

export default function Home() {
  const {
    user: { uid },
    isLoggedIn,
  } = useUser();
  const [isOpenDialog, setIsOpenDialog] = useState(false);

  const [searchTitle, setSearchTitled] = useState<string>("");

  const [chooseType, setChooseType ] = useState<string>("all");

  const { data: isAdmin } = useQuery({
    queryKey: ["admin", uid],
    queryFn: () => getIsAdmin(uid),
    enabled: !!uid,
  });

  const { data: auctions } = useQuery({
    queryKey: ["auctions"],
    queryFn: () => getAuctions(),
  });

  const SearchTokenHandler = (tokenTitle: string) => {
    setSearchTitled(tokenTitle);
  };

  const ChooseTokenTypeHandler = (tokenType: string) => {
    setChooseType(tokenType);
  }

  const isAdminAndLogged = isAdmin && isLoggedIn;

  const closeDialog = () => setIsOpenDialog(false);

  const openDialog = () => setIsOpenDialog(true);

  const filteredAuctionsbyType: Auction[] | undefined = auctions?.filter(
    (auction) => {
        return auction.type === chooseType || chooseType === "all";
    }
  )

  const filteredAuctions: Auction[] | undefined = filteredAuctionsbyType?.filter(
    (auction) => {
      return auction.title.toLowerCase().includes(searchTitle.toLowerCase());
    }
  );

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Overlay type="home">
          <AuctionSearch onSearchFilter={SearchTokenHandler} onTypeFilter={ChooseTokenTypeHandler}/>
          <div className="grid place-content-center grid-cols-4 gap-8 mx-16">
            {filteredAuctions?.map((auction, idx) => (
              <AuctionComponent key={idx} auction={auction} />
            ))}
          </div>
        </Overlay>
      </Layout>
      <>{!!isAdminAndLogged && <AddAuctionBtn openDialog={openDialog} />}</>
      <AddAuctionDialog isOpen={isOpenDialog} close={closeDialog} />
    </>
  );
}
