import { useQuery } from "@tanstack/react-query";
import Head from "next/head";
import { useState } from "react";
import AddAuctionBtn from "../components/add-auction-btn.component";
import AddAuctionDialog from "../components/add-auction-dialog.component";
import Auction from "../components/auction.component";
import AuctionSearch from "../components/auctionSearch.component";
import Layout from "../components/layout.component";
import Overlay from "../components/overlay.component";
import { useUser } from "../hooks/use-user.hook";
import {
  getAuctions,
  getIsAdmin,
  getTokensByUid,
} from "../utils/firebase.util";
import { Token } from "../utils/types.util";

export default function Home() {
  const {
    user: { uid },
    isLoggedIn,
  } = useUser();
  const [isOpenDialog, setIsOpenDialog] = useState(false);

  const { data: isAdmin } = useQuery({
    queryKey: ["admin", uid],
    queryFn: () => getIsAdmin(uid),
    enabled: !!uid,
  });

  const { data: auctions } = useQuery({
    queryKey: ["auctions"],
    queryFn: () => getAuctions(),
  });

  const isAdminAndLogged = isAdmin && isLoggedIn;

  const closeDialog = () => setIsOpenDialog(false);

  const openDialog = () => setIsOpenDialog(true);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Overlay type="home">
          <AuctionSearch />
          <div className="grid place-content-center grid-cols-4 mx-16">
            {auctions?.map((auction, idx) => (
              <Auction key={idx} auction={auction} />
            ))}
          </div>
        </Overlay>
      </Layout>
      <>{!!isAdminAndLogged && <AddAuctionBtn openDialog={openDialog} />}</>
      <AddAuctionDialog isOpen={isOpenDialog} close={closeDialog} />
    </>
  );
}
