import Head from "next/head";
import {
  createAndAddWallet,
  getUserByUsername,
} from "../../utils/firebase.util";
import Layout from "../../components/layout.component";
import Overlay from "../../components/overlay.component";
import Image from "next/image";
import Link from "next/link";
import Button from "../../components/button.component";
import { fetchNewWallet } from "../../utils/fetchers.util";

export async function getServerSideProps({ params: { username } }: any) {
  const profileUser = await getUserByUsername(username);

  const { uid, avatar, account_address, account_balance } = profileUser;

  return {
    props: {
      profileUser: { uid, username, avatar, account_address, account_balance },
    },
  };
}

type Props = {
  profileUser: {
    uid: string;
    username: string;
    avatar: string;
    account_address: string;
    account_balance: string;
  };
};

export default function UserPage({ profileUser }: Props) {
  const { uid, username, avatar, account_address, account_balance } =
    profileUser;

  return (
    <>
      <Head>
        <title>User</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Overlay>
          <section className="card mt-12">
            <div className="w-full flex gap-8">
              <Link href={`/users/${username}`} className="w-32 h-32 relative">
                <Image src={avatar!} alt="avatar" fill />
              </Link>
              <div className="flex flex-col gap-6">
                <div>
                  <p className="text-xl text-primary">
                    Username:
                    <span className="ml-4 text-lg text-black font-mono ">
                      {username}
                    </span>
                  </p>
                </div>
                {account_address ? (
                  <>
                    <div>
                      <p className="text-xl text-primary">
                        Account address:
                        <span className="ml-4 text-lg text-black font-mono ">
                          {account_address}
                        </span>
                      </p>
                    </div>
                    <div>
                      <p className="text-xl text-primary">
                        Account balance:
                        <span className="ml-4 text-lg text-black font-mono ">
                          {account_balance}
                        </span>
                      </p>
                    </div>
                  </>
                ) : (
                  <div className="h-full grid place-content-center">
                    <Button
                      className="w-full"
                      onClick={() => createAndAddWallet(uid)}
                    >
                      Create Wallet
                    </Button>
                  </div>
                )}
              </div>
            </div>
          </section>
        </Overlay>
      </Layout>
    </>
  );
}
